CREATE DATABASE `siakad`;

CREATE TABLE MataKuliah (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    Nama VARCHAR(255) NOT NULL,
    Kode CHAR(5) NOT NULL,
    Deskripsi TEXT
);

CREATE TABLE Dosen (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    Nama VARCHAR(255) NOT NULL,
    NIDN CHAR(8) NOT NULL,
    JenjangPendidikan ENUM("S2","S3") NOT NULL
);

CREATE TABLE Mahasiswa (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    Nama VARCHAR(255) NOT NULL,
    NIM CHAR(10) NOT NULL,
    ProgramStudi VARCHAR(255) NOT NULL
);